#!/bin/bash

sed -i "s|{{clientid}}|$CLIENTID|g" $APPLICATIONCONFFILEPATH
sed -i "s|{{clientsecret}}|$CLIENTSECRET|g" $APPLICATIONCONFFILEPATH
sed -i "s|{{tenant-id}}|$TENANTID|g" $APPLICATIONCONFFILEPATH
sed -i "s|{{bearertoken}}|$BEARERTOKEN|g" $APPLICATIONCONFFILEPATH
sed -i "s|{{scope}}|$SCOPE|g" $APPLICATIONCONFFILEPATH
sed -i "s|{{oauthhost}}|$OAUTHHOST|g" $APPLICATIONCONFFILEPATH
sed -i "s|{{apimSubscriptionKey}}|$APIMSUBSCRIPTIONKEY|g" $APPLICATIONCONFFILEPATH
sed -i "s|{{hostnameWPPSA}}|$HOSTNAMEWPPSA|g" $APPLICATIONCONFFILEPATH
sed -i "s|{{loadTestDuration}}|$LOADTESTDURATION|g" $APPLICATIONCONFFILEPATH
sed -i "s|{{scn01ArchiveAllProductionStores}}|$SCN01ARCHIVEALLPRODUCTIONSTORES|g" $APPLICATIONCONFFILEPATH
sed -i "s|{{scn02ArchiveLargeProductionStore}}|$SCN02ARCHIVELARGEPRODUCTIONSTORE|g" $APPLICATIONCONFFILEPATH
sed -i "s|{{scn03ArchiveMediumProductionStore}}|$SCN03ARCHIVEMEDIUMPRODUCTIONSTORE|g" $APPLICATIONCONFFILEPATH
sed -i "s|{{scn04ArchiveSmallProductionStore}}|$SCN04ARCHIVESMALLPRODUCTIONSTORE|g" $APPLICATIONCONFFILEPATH
sed -i "s|{{scn05CreateProduction}}|$SCN05CREATEPRODUCTION|g" $APPLICATIONCONFFILEPATH
sed -i "s|{{scn06ListProductions}}|$SCN06LISTPRODUCTIONS|g" $APPLICATIONCONFFILEPATH
sed -i "s|{{scn07RestoreLargeProduction}}|$SCN07RESTORELARGEPRODUCTION|g" $APPLICATIONCONFFILEPATH
sed -i "s|{{scn08RestoreMediumProduction}}|$SCN08RESTOREMEDIUMPRODUCTION|g" $APPLICATIONCONFFILEPATH
sed -i "s|{{scn09RestoreSmallProduction}}|$SCN09RESTORESMALLPRODUCTION|g" $APPLICATIONCONFFILEPATH
sed -i "s|{{scn10ListProductionStores}}|$SCN10LISTPRODUCTIONSTORES|g" $APPLICATIONCONFFILEPATH
sed -i "s|{{scn11MakeOfflineLargeProduction}}|$SCN11MAKEOFFLINELARGEPRODUCTION|g" $APPLICATIONCONFFILEPATH
sed -i "s|{{scn12MakeOfflineMediumProduction}}|$SCN12MAKEOFFLINEMEDIUMPRODUCTION|g" $APPLICATIONCONFFILEPATH
sed -i "s|{{scn13MakeOfflineSmallProduction}}|$SCN13MAKEOFFLINESMALLPRODUCTION|g" $APPLICATIONCONFFILEPATH
#sed -i "s|{{targetRPS}}|$TARGETRPS|g" $APPLICATIONCONFFILEPATH
#sed -i "s|{{productionStoreLarge}}|$PRODUCTIONSTORELARGE|g" $APPLICATIONCONFFILEPATH
#sed -i "s|{{productionStoreMedium}}|$PRODUCTIONSTOREMEDIUM|g" $APPLICATIONCONFFILEPATH
#sed -i "s|{{productionStoreSmall}}|$PRODUCTIONSTORESMALL|g" $APPLICATIONCONFFILEPATH
#sed -i "s|{{productionStoreLargeContainer}}|$PRODUCTIONSTORELARGECONTAINER|g" $APPLICATIONCONFFILEPATH
#sed -i "s|{{productionStoreMediumContainer}}|$PRODUCTIONSTOREMEDIUMCONTAINER|g" $APPLICATIONCONFFILEPATH
#sed -i "s|{{productionStoreSmallContainer}}|$PRODUCTIONSTORESMALLCONTAINER|g" $APPLICATIONCONFFILEPATH
#sed -i "s|{{productionLargeGUID}}|$PRODUCTIONLARGEGUID|g" $APPLICATIONCONFFILEPATH
#sed -i "s|{{productionMediumGUID}}|$PRODUCTIONMEDIUMGUID|g" $APPLICATIONCONFFILEPATH
#sed -i "s|{{productionSmallGUID}}|$PRODUCTIONSMALLGUID|g" $APPLICATIONCONFFILEPATH

echo "$(cat $APPLICATIONCONFFILEPATH)"