//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpp.StorageAutomation.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class APIRoutes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal APIRoutes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wpp.StorageAutomation.Tests.Properties.APIRoutes", typeof(APIRoutes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/users.
        /// </summary>
        internal static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /datamovement/production-stores/archive.
        /// </summary>
        internal static string ArchiveAllProductionstores {
            get {
                return ResourceManager.GetString("ArchiveAllProductionstores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /datamovement/production-stores/{0}/productions/archive.
        /// </summary>
        internal static string ArchiveAProductionstore {
            get {
                return ResourceManager.GetString("ArchiveAProductionstore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /productionstore/production-stores.
        /// </summary>
        internal static string CreateAProductionStore {
            get {
                return ResourceManager.GetString("CreateAProductionStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /prodcontroller/production-stores/{0}/productions/.
        /// </summary>
        internal static string CreateProduction {
            get {
                return ResourceManager.GetString("CreateProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /prodcontroller/production-stores/{0}/productions.
        /// </summary>
        internal static string ListProductions {
            get {
                return ResourceManager.GetString("ListProductions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /datamovement/production-stores/{0}/productions/{1}/make-offline.
        /// </summary>
        internal static string MakeProductionOffline {
            get {
                return ResourceManager.GetString("MakeProductionOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /datamovement/production-stores/{0}/productions/{1}/restore.
        /// </summary>
        internal static string RestoreProduction {
            get {
                return ResourceManager.GetString("RestoreProduction", resourceCulture);
            }
        }
    }
}
