//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpp.StorageAutomation.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wpp.StorageAutomation.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xpath://span[contains(@class, &apos;ms-MessageBar&apos;)]/span.
        /// </summary>
        internal static string BannerMessage {
            get {
                return ResourceManager.GetString("BannerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xpath://button[@aria-label=&apos;{0}&apos;].
        /// </summary>
        internal static string ButtonByArialabel {
            get {
                return ResourceManager.GetString("ButtonByArialabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btn_{0}.
        /// </summary>
        internal static string ButtonById {
            get {
                return ResourceManager.GetString("ButtonById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xpath://button[@title=&apos;{0}&apos;].
        /// </summary>
        internal static string ButtonByTitle {
            get {
                return ResourceManager.GetString("ButtonByTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xpath://button[@title=&apos;{0}&apos;]/preceding-sibling::button[1].
        /// </summary>
        internal static string CollapseExpandButton {
            get {
                return ResourceManager.GetString("CollapseExpandButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xpath://*[@data-automation-key=&apos;{0}&apos;].
        /// </summary>
        internal static string ColumnListByName {
            get {
                return ResourceManager.GetString("ColumnListByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xpath://*[@data-item-key=&quot;{0}&quot;].
        /// </summary>
        internal static string ColumnName {
            get {
                return ResourceManager.GetString("ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[contains(@id,&apos;{0}&apos;)][@disabled].
        /// </summary>
        internal static string DisabledElement {
            get {
                return ResourceManager.GetString("DisabledElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[text()=&apos;{0} cannot be empty. Please enter a {1}.&apos;].
        /// </summary>
        internal static string EmptyMessage {
            get {
                return ResourceManager.GetString("EmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xpath://label[@for=&apos;txt_{0}&apos;]/parent::div/following-sibling::span.
        /// </summary>
        internal static string FieldMessage {
            get {
                return ResourceManager.GetString("FieldMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xpath://*[text()=&apos;{0}&apos;].
        /// </summary>
        internal static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to img_Logo.
        /// </summary>
        internal static string HomePageLogo {
            get {
                return ResourceManager.GetString("HomePageLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idp-discovery-{0}.
        /// </summary>
        internal static string IdpControl {
            get {
                return ResourceManager.GetString("IdpControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xpath://*[text()=&apos;{0}&apos;]/../div[6]/div/div[2]/button.
        /// </summary>
        internal static string MoreOptionsButtonByProductionName {
            get {
                return ResourceManager.GetString("MoreOptionsButtonByProductionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xpath:(btn_{0})[{1}].
        /// </summary>
        internal static string MultipleButtonById {
            get {
                return ResourceManager.GetString("MultipleButtonById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to okta-signin-{0}.
        /// </summary>
        internal static string OktaControl {
            get {
                return ResourceManager.GetString("OktaControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[text()=&apos;Create Production&apos;].
        /// </summary>
        internal static string PageHeading {
            get {
                return ResourceManager.GetString("PageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xpath:(//*[@data-automation-key=&apos;{0}&apos;])[{1}].
        /// </summary>
        internal static string ProductionDetailsInGrid {
            get {
                return ResourceManager.GetString("ProductionDetailsInGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xpath://button[@title=&apos;{0}&apos;]/ancestor::li/ul/li//button.
        /// </summary>
        internal static string ProductionStoresListByRegion {
            get {
                return ResourceManager.GetString("ProductionStoresListByRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xpath://ul/li/ul/li/div/button.
        /// </summary>
        internal static string ProductionStoresOnUI {
            get {
                return ResourceManager.GetString("ProductionStoresOnUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xpath://nav[@role=&apos;navigation&apos;]/div/div/ul/li/div.
        /// </summary>
        internal static string RegionList {
            get {
                return ResourceManager.GetString("RegionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xpath://*[contains(@class,&apos;ms-Spinner-label&apos;) and contains(text(),&apos;{0}&apos;)].
        /// </summary>
        internal static string Spinner {
            get {
                return ResourceManager.GetString("Spinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txt_{0}.
        /// </summary>
        internal static string TextBoxById {
            get {
                return ResourceManager.GetString("TextBoxById", resourceCulture);
            }
        }
    }
}
