//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpp.StorageAutomation.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserGroupDetails {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserGroupDetails() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wpp.StorageAutomation.Tests.Properties.UserGroupDetails", typeof(UserGroupDetails).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRP-DEVH-AUTHz-WPP-CloudStudio-testproductionstorea-Managers.
        /// </summary>
        internal static string Defaultmg {
            get {
                return ResourceManager.GetString("Defaultmg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRP-DEVH-AUTHz-WPP-CloudStudio-testproductionstorea-Users.
        /// </summary>
        internal static string Defaultug {
            get {
                return ResourceManager.GetString("Defaultug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRP-DEVH-AUTHz-WPP-CloudStudio-testproductionstorea-Managers,GRP-DEVH-AUTHz-WPP-CloudStudio-testarchiveps2-Managers.
        /// </summary>
        internal static string testarchiveps2mg {
            get {
                return ResourceManager.GetString("testarchiveps2mg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRP-DEVH-AUTHz-WPP-CloudStudio-testproductionstorea-Users,GRP-DEVH-AUTHz-WPP-CloudStudio-testarchiveps2-Users.
        /// </summary>
        internal static string testarchiveps2ug {
            get {
                return ResourceManager.GetString("testarchiveps2ug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRP-DEVH-AUTHz-WPP-CloudStudio-testproductionstorea-Managers.
        /// </summary>
        internal static string testproductionstoreamg {
            get {
                return ResourceManager.GetString("testproductionstoreamg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRP-DEVH-AUTHz-WPP-CloudStudio-testproductionstorea-Users.
        /// </summary>
        internal static string testproductionstoreaug {
            get {
                return ResourceManager.GetString("testproductionstoreaug", resourceCulture);
            }
        }
    }
}
